version: '3'

services:
  bbdd:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: ddd
      MYSQL_USER: ddd
      MYSQL_PASSWORD: ddd
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3333:3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9001"
    volumes:
      - ./:/var/www/web
    depends_on:
      - bbdd

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/web
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - ddd_network
      - default

volumes:
  mysql-data: {}

networks:
  ddd_network:
    external: true